services:
  api:
    build: .
    container_name: monitoring-api
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ENABLE_CLOUDWATCH=false
      - CLOUDWATCH_LOG_GROUP=network-service-monitoring-platform
      - CLOUDWATCH_STREAM_NAME=fastapi-monitoring-service
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: monitoring-redis
    ports:
      - "6379:6379"